name = "TimeseriesUtilities"
uuid = "31d49243-0742-49c1-b8d2-db113b74581e"
version = "0.1.5"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["docs", "test"]

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
HybridArrays = "1baab800-613f-4b0a-84e4-9cd3431bfbb9"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
RollingWindowArrays = "d191faf8-5603-4116-bb4f-9585dee8559b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
VectorizedStatistics = "3b853605-1c98-4422-8364-4bd93ee0529e"

[weakdeps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
SpaceDataModel = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"

[extensions]
TimeseriesUtilitiesAxisKeysExt = "AxisKeys"
TimeseriesUtilitiesSpaceDataModelExt = "SpaceDataModel"

[compat]
AxisKeys = "0.2"
DSP = "0.7, 0.8"
DataInterpolations = "7, 8"
Dates = "1"
DimensionalData = "0.29"
HybridArrays = "0.4.16"
LinearAlgebra = "1"
NaNStatistics = "0.6"
RollingWindowArrays = "1.0.1"
SpaceDataModel = "0.2"
StaticArrays = "1.9"
Statistics = "1"
Unitful = "1"
VectorizedStatistics = "0.5"
julia = "1.10"
